### ISSUE TITLE
Add order details

### ISSUE THREAD

**Issue by lodagro** [CivicLabsBelgium/influencair-pcb#1]
Would it be possible to add order details for [https://www.seeedstudio.com](url) ?

Are the default settings ok? Or are other values needed?
Below is a screenshot for the default values.

![screenshot](https://image.ibb.co/kAhvSo/Untitled.png)

Thanks.

**Comment by Cinezaster** [comment]
@lodagro https://www.seeedstudio.com/Influencair-g-1130877
I did not change any setting except for the color and quantity.

**Comment by lodagro** [comment]
@Cinezaster Thanks, i placed an order (using the above link, b.t.w for which the board dimensions are different compared to uploading the gerber zip archive)

**Comment by Cinezaster** [comment]
@lodagro I know, for some reason it shows a different board dimension sometimes if you upload the zip file.

**Comment by lodagro** [comment]
@Cinezaster Meanwhile the  boards i ordered arrived, i assembled two measurement stations. Very convenient. 

:thumbsup:
